name: Build & Tests
on: [push, pull_request]
jobs:
  macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_14.0.app
      - name: Build and Test SPM
        run: swift test
      - name: Update Cocoa Pods repo
        run: pod repo update
      - name: Build and Test CocoaPods
        run: pod lib lint --allow-warnings --fail-fast
  linux:
    runs-on: ubuntu-latest
    container:
      image: swift:5.8.1-jammy
      options: --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --security-opt apparmor=unconfined
    steps:
      - name: Install latest curl
        run: |
          sudo apt update && sudo apt install wget
          wget -O curl.deb http://ftp.debian.org/debian/pool/main/c/curl/libcurl4_7.88.1-10_amd64.deb
          sudo dpkg -i curl.deb
          rm curl.deb
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Test
        run: swift test
